In [29]:
import pandas as pd
frame_list = pd.DataFrame([[2,4,6,7],[3,5,5,9]])
print(frame_list.head(4))

   0  1  2  3
0  2  4  6  7
1  3  5  5  9


In [49]:
import numpy as np
import pandas as pd

## -- Numpy et Pandas ( october 20/10/2020)



## --- pratique 1:
## construire un vecteur avec [3,4,5,6]
## assigner resultat a la variable vector
## indice : np.array([3,4,5,6])

vector = np.array([3,4,5,6])


## --- pratique 2:
## construire une matrice  depuis la liste de listes [[2,5,15],[20,50,50],[34,99,45]]
## Afficher les resultats
## assigner le resultat a la variable matrix 
matrix = np.array([[2,5,15],[20,50,50],[34,99,45]])
print(matrix)

## --- pratique 3:
## Donner la taille du tableau [1,2,3,4]suivant puis changer sa taille
## Afficher les resultats
## indication : shape, reshape

tab1 = np.array([1,2,3,4])
print(np.shape(tab1))
tab2 = tab1.reshape(4,1)
print(tab2)

## --- pratique 4:
## Donner la taille de la matrice [[5,10,15], [20,25,30], [40,45,50]] suivant puis changer sa taille 
## Afficher les resultats
## indication : shape, reshape
tab3= np.array([[5,10,15],[20,25,30],[40,45,50]])
print(tab3.shape)
tab4 = tab3.reshape(1,9)

## --- pratique 5:
## Executer le code suivant ( en specifiant le path du fichier)
#import numpy as np
#fichier = np.genfromtxt("data_numpy.csv", delimiter=",")
## Utiliser les fonctions type() et print() pour afficher le type de fichier 

## --- pratique 6:
## creer un vecteur random ayant 4 valeurs
vec2 = np.random.random(size=4)
## creer une matrice random de taille (2X2)
matrix2 = np.random.random(size=(2,2))

## --- pratique 7:
# creer un vecteur depuis la liste[1, 2, 3, 4] et afficher son type
vec3 = np.array([1,2,3,4])
print(type(vec3))


## --- pratique 9
#Importer la librairie pandas.
#Utiliser la fonction pandas.read_csv() pour lire le fichier "food_info.csv" 
#Utiliser les fonctions type() et print() pour afficher le type de food_info 
#import pandas as pd
food_info = pd.read_csv("./data/food_info.csv")
#print(type(food_info))



##--- pratique 10
#Afficher la 1000e ligne du dataframe food_info
row = food_info.loc[999]

#solution
#row_1000 = food_info.loc[999]
#print(row_1000)


##--- pratique 11
#Assigner la colonne "protein_(g)" à la variable protein.
protein = food_info["Protein_(g)"]
#Assigner la colonne "Cholestrl_(mg)" à la variable cholesterol.
cholesterol = food_info["Cholestrl_(mg)"]
#Afficher les résultats.
print(protein, cholesterol)



##--- pratique 12
#Sélectionner les colonnes 'Shrt__Desc', 'Selenium_(mcg)' et 'Thiamin_(mg)' 
#et assigner le dataframe résultant à la variable selenium_thiamin.
selenium_thiamin = food_info[['Shrt_Desc', 'Selenium_(mcg)', 'Thiamin_(mg)']]
#Afficher le résultat.
print(selenium_thiamin)



## --- pratique 13
# 1) Sélectionner et afficher seulement les colonnes qui utilisent comme unité de mesure les grammes 
#(c'est à dire qui se terminent par "(g)"). Pour cela:
#Utiliser l'attribut columns pour retourner le nom des colonnes du dataframe food_info 
#et convertir en liste utilisant la méthode tolist()

## 2) Créer une nouvelle liste qu'on nommera gram__columns, contenant seulement les colonnes se terminant 
##  par "(g)". Indice: la méthode endswith() retourne True si l'objet sur lequel on l'applique se termine
## par l'élément entre parenthèses. ex: total_(g).endswith("(g)") retourne True. Une boucle for est fortement conseillé pour parcourir tous les noms de colonne.

## 3) Sélectionner les colonnes de gram_columns pour le dataframe food_info et assigner le dataframe résultat 
## à la variable gram_df 

## 4) Afficher les 3 premières valeurs de ce dataframe gram_df

## solution
##col_names = food_info.columns.tolist()
##gram_columns = []

##for c in col_names:
  ##  if c.endswith("(g)"):
   ##     gram_columns.append(c)
        
##gram_df = food_info[gram_columns]

##gram_df.head(3)



##--- pratique 14
#Lire le dataset 'fandango_score_comparison' dans le dataframe fandango.
#Retourner un DataFrame contenant seulement la première et la dernière ligne et assigner le résultat à la variable first_last.
#Afficher le résultat.

###--- solution
#import pandas as pd
#fandango = pd.read_csv('fandango_score_comparison.csv')
#first = 0
#last = fandango.shape[0] - 1
#first_last = fandango.iloc[[first,last]]
#first_last


##--- pratique 15
#Lire le fichier "fandango_score_comparison.csv" dans un dataframe qu'on nommera fandango.
#Afficher les 2 premières lignes de fandango.

## solution
##import pandas as pd
##fandango = pd.read_csv('fandango_score_comparison.csv')
##fandango.head(2)

##---- pratique 16
##Sélectionner la colonne "FILM" et assigner la à la variable series_film puis afficher les 5 premières valeurs.
#Faire de même avec la colonne "RottenTomatoes" et assigner la à la variable series_rt puis afficher les 5 premières valeurs.

## solution
##series_film = fandango['FILM']
##print(series_film[0:5])
##series_rt = fandango['RottenTomatoes']
##print(series_rt[0:5])


###--- pratique 17
##Créer un objet Series qu'on nommera series_custom qui aura 
##un index de chaines de caractères (basé sur le nom des films 
##qu'on assignera à la variable film_names) et contiendra toutes 
##les notes RottenTomatoes de series_rt qu'on assignera à la variable rt_scores.

## solution
# importer l'objet Series depuis pandas
#from pandas import Series

#film_names = series_film.values
#rt_scores = series_rt.values
#series_custom = Series(rt_scores, index=film_names)


###--- pratique 18
##Créer la liste original_index contenant l'index actuel à partir de l'attribut index.
##Trier cet index en utilisant la méthode sorted() et assigner le résultat à la variable sorted_index.
##Puis appliquer la méthode reindex() à notre Series custom_series afin de réindexer selon l'index de sorted_index.
##Stocker le résultat dans la variable sorted_by_index.
##Afficher le résultat.

## solution
##original_index = series_custom.index
##sorted_index = sorted(original_index)
##sorted_by_index = series_custom.reindex(sorted_index)
##print(sorted_by_index)


###--- pratique 19
##Trier la Series series_custom par index en utilisant la méthode sort_index() et assigner le résultat à la variable sc2.
##Trier la Series series_custom par valeurs et assigner le résultat à la variable sc3.
##Afficher les 10 premières valeurs de sc2 et sc3.

## solution
##sc2 = series_custom.sort_index()
##sc3 = series_custom.sort_values()
##print(sc2[0:10])
#print(sc3[0:10])

###--- pratique 20
##Assigner à la variable criteria_one le critère des valeurs de series_custom supérieurs à 50.
##Assigner à la variable criteria_two le critère des valeurs de series_custom inférieurs à 75.
##Retourner un nouvel objet Series filtré qu'on nommera both_criteria qui contient seulement les valeurs pour lesquelles les 2 critères sont vrais.
##Afficher ce dernier résultat.

##-- solution
##criteria_one = series_custom > 50
##criteria_two = series_custom < 75
##both_criteria = series_custom[criteria_one & criteria_two]
##both_criteria

[[ 2  5 15]
 [20 50 50]
 [34 99 45]]
(4,)
[[1]
 [2]
 [3]
 [4]]
(3, 3)
<class 'numpy.ndarray'>
0        0.85
1        0.85
2        0.28
3       21.40
4       23.24
        ...  
8613    18.50
8614    20.54
8615     0.00
8616    16.10
8617    19.80
Name: Protein_(g), Length: 8618, dtype: float64 0       215.0
1       219.0
2       256.0
3        75.0
4        94.0
        ...  
8613     95.0
8614     41.0
8615      0.0
8616     50.0
8617     50.0
Name: Cholestrl_(mg), Length: 8618, dtype: float64


In [52]:

## --- pratique 13
# 1) Sélectionner et afficher seulement les colonnes qui utilisent comme unité de mesure les grammes 
#(c'est à dire qui se terminent par "(g)"). Pour cela:
#Utiliser l'attribut columns pour retourner le nom des colonnes du dataframe food_info 
#et convertir en liste utilisant la méthode tolist()

## 2) Créer une nouvelle liste qu'on nommera gram__columns, contenant seulement les colonnes se terminant 
##  par "(g)". Indice: la méthode endswith() retourne True si l'objet sur lequel on l'applique se termine
## par l'élément entre parenthèses. ex: total_(g).endswith("(g)") retourne True. Une boucle for est fortement conseillé pour parcourir tous les noms de colonne.

## 3) Sélectionner les colonnes de gram_columns pour le dataframe food_info et assigner le dataframe résultat 
## à la variable gram_df 

## 4) Afficher les 3 premières valeurs de ce dataframe gram_df

print(food_info.columns.tolist())

['NDB_No', 'Shrt_Desc', 'Water_(g)', 'Energ_Kcal', 'Protein_(g)', 'Lipid_Tot_(g)', 'Ash_(g)', 'Carbohydrt_(g)', 'Fiber_TD_(g)', 'Sugar_Tot_(g)', 'Calcium_(mg)', 'Iron_(mg)', 'Magnesium_(mg)', 'Phosphorus_(mg)', 'Potassium_(mg)', 'Sodium_(mg)', 'Zinc_(mg)', 'Copper_(mg)', 'Manganese_(mg)', 'Selenium_(mcg)', 'Vit_C_(mg)', 'Thiamin_(mg)', 'Riboflavin_(mg)', 'Niacin_(mg)', 'Vit_B6_(mg)', 'Vit_B12_(mcg)', 'Vit_A_IU', 'Vit_A_RAE', 'Vit_E_(mg)', 'Vit_D_mcg', 'Vit_D_IU', 'Vit_K_(mcg)', 'FA_Sat_(g)', 'FA_Mono_(g)', 'FA_Poly_(g)', 'Cholestrl_(mg)']
